#!/bin/sh

set -e

[ -f /etc/default/xformation-server ] && . /etc/default/xformation-server

IS_UPGRADE=false


case "$1" in
	configure)
	[ -z "$XFORMATION_USER" ] && XFORMATION_USER="xformation"
	[ -z "$XFORMATION_GROUP" ] && XFORMATION_GROUP="xformation"
	if ! getent group "$XFORMATION_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$XFORMATION_GROUP" --quiet
	fi
	if ! id $XFORMATION_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/xformation --no-create-home \
		--ingroup "$XFORMATION_GROUP" --disabled-password --shell /bin/false \
		"$XFORMATION_USER"
	fi

	# Set user permissions on /var/log/xformation, /var/lib/xformation
	mkdir -p /var/log/xformation /var/lib/xformation
	chown -R $XFORMATION_USER:$XFORMATION_GROUP /var/log/xformation /var/lib/xformation
	chmod 755 /var/log/xformation /var/lib/xformation

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/xformation/conf/sample.ini $CONF_FILE
    cp /usr/share/xformation/conf/ldap.toml /etc/xformation/ldap.toml
  fi

  if [ ! -f $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/xformation/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/xformation/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi 

	# configuration files should not be modifiable by xformation user, as this can be a security issue
	chown -Rh root:$XFORMATION_GROUP /etc/xformation/*
	chmod 755 /etc/xformation
	find /etc/xformation -type f -exec chmod 640 {} ';'
	find /etc/xformation -type d -exec chmod 755 {} ';'

  # If $1=configure and $2 is set, this is an upgrade
  if [ "$2" != "" ]; then
    IS_UPGRADE=true
  fi

  if [ "x$IS_UPGRADE" != "xtrue" ]; then
    if command -v systemctl >/dev/null; then
      echo "### NOT starting on installation, please execute the following statements to configure xformation to start automatically using systemd"
      echo " sudo /bin/systemctl daemon-reload"
      echo " sudo /bin/systemctl enable xformation-server"
      echo "### You can start xformation-server by executing"
      echo " sudo /bin/systemctl start xformation-server"
    elif command -v update-rc.d >/dev/null; then
      echo "### NOT starting xformation-server by default on bootup, please execute"
      echo " sudo update-rc.d xformation-server defaults 95 10"
      echo "### In order to start xformation-server, execute"
      echo " sudo service xformation-server start"
    fi
  elif [ "$RESTART_ON_UPGRADE" = "true" ]; then

    echo -n "Restarting xformation-server service..."

    if command -v systemctl >/dev/null; then
      systemctl daemon-reload
      systemctl restart xformation-server || true
    elif [ -x /etc/init.d/xformation-server ]; then
      if command -v invoke-rc.d >/dev/null; then
        invoke-rc.d xformation-server restart || true
      else
        /etc/init.d/xformation-server restart || true
      fi
    fi
    echo " OK"

	fi
	;;
esac
